#ifndef LOUPGAROUCORE_GLOBAL_H
#define LOUPGAROUCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LOUPGAROUCORE_LIB
# define LOUPGAROUCORE_EXPORT Q_DECL_EXPORT
#else
# define LOUPGAROUCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // LOUPGAROUCORE_GLOBAL_H
